name: Build and Deploy to GKE

on:
  push:
    branches: ["*"]
  workflow_dispatch:

env:
  IMAGE_REGISTRY_PROJECT: mv-service-project-7215

jobs:
  build-image:

    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Compute Image Tag
      id: image
      run: |
        # use bash variable expression to get the substring
        export GIT_PR_SHA="${{ github.sha }}"
        export GIT_PR_SHA_SHORT="${GIT_PR_SHA:0:7}"

        echo "::set-output name=tag::${GIT_PR_SHA_SHORT}"
    outputs:
      image_tag: ${{ steps.image.outputs.tag }}

  trigger-deployment:
    name: Trigger Deployment
    runs-on: ubuntu-latest
    needs: [build-image]

    steps:
    - name: Check CI Outputs
      run: |
        export IMAGE_TAG="${{ needs.build-image.outputs.image_tag }}"
        export APP="${{ github.repository }}"
        echo $IMAGE_TAG
        echo $APP
        
    - name: Checkout CD repo
      uses: actions/checkout@master
      with:
        repository: obrienalaribe/k8s-manifests
     
    - name: Create repo folder
      run: |-
        mkdir -p ${GITHUB_REPOSITORY}
        
#     - name: Setup tmate session
#       uses: mxschmitt/action-tmate@v3.6
      
    - name: Stage manifests
      run: |-
        ls -lt ${APP}
        touch $IMAGE_TAG > ${APP}/version
        git add ${APP}/version
        
    - name: Push changes
      uses: actions-go/push@v1
      with:
        commit-message: "This is a commit from CI process"
        token: ${{ secrets.CD_REPO_TOKEN }}


