name: Build and Deploy to GKE

on:
  push:
    branches: ["*"]
  workflow_dispatch:

env:
  IMAGE_REGISTRY_PROJECT: mv-paid-images-d3d34

jobs:
  build-image:

    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Compute Image Tag
      id: image
      run: |
        # use bash variable expression to get the substring
        export GIT_PR_SHA="${{ github.sha }}"
        export GIT_PR_SHA_SHORT="${GIT_PR_SHA:0:7}"

        echo "::set-output name=tag::${GIT_PR_SHA_SHORT}"
    outputs:
      image_tag: ${{ steps.image.outputs.tag }}

  trigger-deployment:
    name: Trigger Deployment
    runs-on: ubuntu-latest
    needs: [build-image]
    
    env:
      K8S_REPO_WORKSPACE: ${{ github.workspace }}/k8s-manifests

    steps:
    - name: Set Job Envs
      run: |
        echo "IMAGE_TAG=${{ needs.build-image.outputs.image_tag }}" >> $GITHUB_ENV
        echo "APP=$(basename ${{ github.repository }})" >> $GITHUB_ENV
        
    - name: Checkout CD repo
      uses: actions/checkout@master
      with:
        repository: obrienalaribe/k8s-manifests
        path: ${K8S_REPO_WORKSPACE}
     
    - name: Create app subfolder
      run: mkdir -p "${K8S_REPO_WORKSPACE}/${APP}"
  
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3.6      

    - name: Update app version
      run: |
        echo $IMAGE_TAG > ${K8S_REPO_WORKSPACE}/${APP}/version
        cd ${K8S_REPO_WORKSPACE}/${APP} && git add version

    - name: Commit & Push
      uses: github-actions-x/commit@v2.8
      with:
        commit-message: "$APP version updated to $IMAGE_TAG"
        github-token: ${{ secrets.CD_REPO_TOKEN }}
        push-branch: ${{ github.ref }}


