name: Build and Deploy to GKE

on:
  pull_request:
    branches: ["main"]
    types: [assigned, opened, synchronize, reopened]

env:
  IMAGE_REGISTRY_PROJECT: mv-paid-images-d3d34

jobs:
  build-image:

    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Compute Image Tag
      id: image
      run: |
        # use bash variable expression to get the substring
        export GIT_PR_SHA="${{ github.sha }}"
        export GIT_PR_SHA_SHORT="${GIT_PR_SHA:0:7}"

        echo "::set-output name=tag::${GIT_PR_SHA_SHORT}"
    outputs:
      image_tag: ${{ steps.image.outputs.tag }}

  trigger-deployment:
    name: Trigger Deployment
    runs-on: ubuntu-latest
    needs: [build-image]
    
    env:
      K8S_REPO_WORKSPACE: ${{ github.workspace }}/k8s-manifests

    steps:
    - name: Dump Github Context
      env:
        GH_CONTEXT: ${{ toJSON(github) }}
      run: echo $GH_CONTEXT
        
    - name: Push new Version to CD
      uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: obrienalaribe
        repo: k8s-manifests
        github_token: ${{ secrets.CD_REPO_TOKEN }}
        workflow_file_name: main.yml
        ref: main
        wait_interval: 5
        inputs: '{"version": "${{ needs.build-image.outputs.image_tag }}"}'
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true
        
