name: Build and Deploy to GKE

on:
  push:
    branches: ["*"]
  workflow_dispatch:

env:
  IMAGE: simple-app
  PROJECT_ID: mv-service-project-7215

jobs:
  build-image:

    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
    
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set env
      run:  echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
    
    - name: Check env
      run: echo $IMAGE_TAG

  trigger-deployment:
    name: Trigger Deployment
    runs-on: ubuntu-latest
    needs: [build-image]

    steps:
    - name: Checkout CD repo
      uses: actions/checkout@master
      with:
        repository: obrienalaribe/k8s-manifests
     
    - name: Create repo folder
      run: |-
        mkdir -p ${GITHUB_REPOSITORY}
        
#     - name: Setup tmate session
#       uses: mxschmitt/action-tmate@v3.6
      
    - name: Stage manifests
      run: |-
        ls -lt ${GITHUB_REPOSITORY}
        touch $IMAGE_TAG > ${GITHUB_REPOSITORY}/version
        git add $GITHUB_REPOSITORY/*
        
    - name: Push changes
      uses: actions-go/push@v1
      with:
        commit-message: "This is a commit from CI process"
        token: ${{ secrets.CD_REPO_TOKEN }}


