name: Build and Deploy to GKE

on:
  push:
    branches: ["*"]
  workflow_dispatch:

env:
  IMAGE_REGISTRY_PROJECT: mv-service-project-7215

jobs:
  build-image:

    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Compute Image Tag
      id: image_tag
      run: |
        # use bash variable expression to get the substring
        export GIT_PR_SHA="${{ github.sha }}"
        export GIT_PR_SHA_SHORT="${GIT_PR_SHA:0:7}"

        echo "::set-output name=git_pr_sha::${GIT_PR_SHA}"
        echo "::set-output name=git_pr_sha_short::${GIT_PR_SHA_SHORT}"
    outputs:
      git_pr_sha: ${{ steps.image_tag.outputs.git_pr_sha }}
      git_pr_sha_short: ${{ steps.image_tag.outputs.git_pr_sha_short }}

  trigger-deployment:
    name: Trigger Deployment
    runs-on: ubuntu-latest
    needs: [build-image]

    steps:
    - name: Check CI Outputs
      run: |
        echo "${{ needs.first-job.outputs.git_pr_sha }}"
        echo "${{ needs.first-job.outputs.git_pr_sha_short }}"
        
    - name: Checkout CD repo
      uses: actions/checkout@master
      with:
        repository: obrienalaribe/k8s-manifests
     
    - name: Create repo folder
      run: |-
        mkdir -p ${GITHUB_REPOSITORY}
        
#     - name: Setup tmate session
#       uses: mxschmitt/action-tmate@v3.6
      
    - name: Stage manifests
      run: |-
        ls -lt ${GITHUB_REPOSITORY}
        touch $IMAGE_TAG > ${GITHUB_REPOSITORY}/version
        git add $GITHUB_REPOSITORY/*
        
    - name: Push changes
      uses: actions-go/push@v1
      with:
        commit-message: "This is a commit from CI process"
        token: ${{ secrets.CD_REPO_TOKEN }}


