name: Remove PR Branch
on:
  pull_request:
    branches: ["*"]
    types: [closed]


jobs:
  remove-pr-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
         git push origin --delete ${{ github.head_ref }}
