name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'SEMANTIC_VERSION_TYPE'
        required: true
        default: 'MINOR'
      home:
        description: 'ENV'
        required: false
        default: 'DEV'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"
